### ISSUE TITLE
.gitmodules needs to be updated

### ISSUE THREAD

**Issue by tfarina** [marcoms/btcwatch#10]
It is still pointing to https://github.com/marcoms/libbtcapi.git.

It was moved into https://github.com/marcoms/libcryptick.git

Btw, it is also stuck at commit 4a2507fc0944ecf93fae4c1e1eba9cb04e7535e3.

Regards,

**Comment by marcoms** [comment]
Thanks for notifying me! libcryptick is in the middle of quite a large rewrite that will make it much more flexible, so I've held off related things 'till I finish it! :+1:

**Comment by marcoms** [comment]
Will get around to this shortly

**Comment by marcoms** [comment]
Apologies for making false claims, this project is pretty much abandoned now... No longer an interest for me :(
