### ISSUE TITLE
Libbtcapi missing

### ISSUE THREAD

**Issue by tfarina** [marcoms/btcwatch#7]
How can we initialize libbtcapi localized in src/lib/libbtcapi? Looks like it is a submodule?

**Comment by marcoms** [comment]
Yes it is a submodule of github.com/marcoms/libbtcapi.git. Sorry I don't understand what you mean by initialise?

**Comment by tfarina** [comment]
'git submodule init' didn't work

**Comment by tfarina** [comment]
My bad, I should have read the submodule documentation earlier. I will try 'git clone --recursive' later tonight.

**Comment by marcoms** [comment]
My mistake - I was confusing a submodule with just a simple clone of the repo, which is what it is - not a submodule, sorry

**Comment by tfarina** [comment]
$ git clone --recursive https://github.com/marcoms/btcwatch.git
Cloning into 'btcwatch'...
remote: Reusing existing pack: 570, done.
remote: Total 570 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (570/570), 208.97 KiB | 190 KiB/s, done.
Resolving deltas: 100% (283/283), done.
No submodule mapping found in .gitmodules for path 'src/lib/libbtcapi'

**Comment by marcoms** [comment]
Thanks for reporting. I suppose I was only testing it on one machine - I'll change it to a submodule when I return from school

**Comment by tfarina** [comment]
Thanks a lot! I will try later tonight.
