### ISSUE TITLE
Tree is dirty after running make

### ISSUE THREAD

**Issue by tfarina** [marcoms/btcwatch#8]
$ git clone --recursive https://github.com/marcoms/btcwatch.git
$ cd btcwatch
$ git status
# On branch master

nothing to commit (working directory clean)
$ ./configure
$ git status
# On branch master
# Untracked files:
# (use "git add <file>..." to include in what will be committed)
# 
# config.log
# config.status
# prefix.txt
# src/include/config.h

nothing added to commit but untracked files present (use "git add" to track)
$ CFLAGS="-DBTC_E_API" make
$ git status
# On branch master
# Changes not staged for commit:
# (use "git add <file>..." to update what will be committed)
# (use "git checkout -- <file>..." to discard changes in working directory)
# (commit or discard the untracked or modified content in submodules)
# 
# modified:   src/lib/libbtcapi (untracked content)
# 
# Untracked files:
# (use "git add <file>..." to include in what will be committed)
# 
# btcwatch
# config.log
# config.status
# prefix.txt
# src/btcutil.o
# src/include/config.h
# src/main
# src/main.o

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by marcoms** [comment]
You can clean up the tree by running `make distclean` which will remove files generated by the configure script as well as those from make

**Comment by marcoms** [comment]
... unless you were suggesting a .gitignore? :)

**Comment by tfarina** [comment]
.gitignore, yep ;)

**Comment by tfarina** [comment]
Thanks, this fixes almost everything.

**Comment by tfarina** [comment]
$ git stautus

# On branch master

# Changes not staged for commit:

# (use "git add <file>..." to update what will be committed)

# (use "git checkout -- <file>..." to discard changes in working directory)

# (commit or discard the untracked or modified content in submodules)

#

# modified:   src/lib/libbtcapi (untracked content)

#
no changes added to commit (use "git add" and/or "git commit -a")

**Comment by tfarina** [comment]
$ git diff
diff --git a/src/lib/libbtcapi b/src/lib/libbtcapi
--- a/src/lib/libbtcapi
+++ b/src/lib/libbtcapi
@@ -1 +1 @@
-Subproject commit 4a2507fc0944ecf93fae4c1e1eba9cb04e7535e3
+Subproject commit 4a2507fc0944ecf93fae4c1e1eba9cb04e7535e3-dirty

**Comment by marcoms** [comment]
Ah yes will add src/lib/libbtcapi to .gitignore too
